name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Create directories
      run: mkdir -p dist
    
    - name: Build binaries
      run: make build-all
    
    - name: List built files
      run: ls -la dist/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        body: |
          ## Orb Version Control System ${{ github.ref_name }}
          
          A Git-like version control system built from scratch in Go!
          
          ### Installation
          
          **Quick Install (Linux/macOS):**
          ```bash
          curl -sSL https://raw.githubusercontent.com/ayushsarode/orb/main/install.sh | bash
          ```
          
          **Manual Installation:**
          1. Download the appropriate binary for your platform
          2. Make it executable: `chmod +x orb-*`
          3. Move to PATH: `sudo mv orb-* /usr/local/bin/orb`
          
          ### Features
          - Initialize repositories (`orb init`)
          - Stage changes (`orb add`) 
          - Create commits (`orb commit`)
          - View history (`orb log`)
          - Branch management (`orb branch`, `orb checkout`)
          
          ### Getting Started
          ```bash
          orb init
          orb add .
          orb commit -m "Initial commit"
          orb log
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}